import { Briefcase, Headphones, Bot, Network, Shield } from "lucide-react";
import { Certification } from "@/components/portfolio/CertificationDetailsModal";
import { Internship } from "@/components/portfolio/InternshipDetailsModal";
import { Project } from "@/components/portfolio/ProjectDetailsModal";

export const onlineCourses = [
  { name: "CyberSecurity 101 ", provider: "Tryhackme", year: "2025" },
  { name: "Global Education Program Focused on AI", provider: "Samsung Innovation Campus", year: "2025" },
];

export const education = [
  {
    degree: "B.S. Software Engineering",
    institution: "The High Private School of Engineering and Technology (ESPRIT)",
    location: "Ariana, Tunisia",
    period: "2023 - Present",
    status: "In Progress",
    description: "Comprehensive software engineering education with focus on cybersecurity, AI, and blockchain technologies.",
    coursework: ["Software Architecture", "Cybersecurity", "AI & Machine Learning", "Blockchain Technology", "DevSecOps"],
    achievements: ["Multiple Pentesting Internships", "Active in IEEE Projects"]
  },
  {
    degree: "Preparatory Studies for Engineering",
    institution: "Faculty of Sciences Monastir",
    location: "Monastir, Tunisia",
    period: "2020 - 2023",
    status: "Graduated",
    description: "Foundational engineering studies preparing for advanced computer science and cybersecurity specialization.",
    coursework: ["Mathematics", "Physics", "Computer Science Fundamentals", "Engineering Principles", "Problem Solving"],
    achievements: ["Strong foundation in STEM subjects"]
  }
];

export const projects: Project[] = [
  {
    title: "Cognicare",
    company: "IEEE",
    period: "December 2025",
    location: "",
    description: "A pioneering digital health platform designed to bridge the gap between clinical developmental assessment and home-based therapy using multimodal AI.",
    icon: Briefcase,
    category: "AI",
    technologies: ["Next.js 14", "Python FastAPI", "Supabase", "OpenCV", "Phi-4 Multimodal Model", "Tailwind CSS"],
    highlights: ["AI-based developmental disorder detection", "Gamified therapy integration", "Real-time progress tracking"],
    status: "Completed",
    images: ["https://res.cloudinary.com/dvmuvjukn/image/upload/v1766057101/Capture_d_%C3%A9cran_2025-12-17_185840_f78uk9.png", "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766057098/Capture_d_%C3%A9cran_2025-12-17_185421_xyh7fm.png" , "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766057091/Capture_d_%C3%A9cran_2025-12-17_184931_nitskg.png" , "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766057091/Capture_d_%C3%A9cran_2025-12-17_185338_wdhvwt.png"],
    githubUrl: "https://github.com/m2l33k/ConiCare"
  },
  {
    title: "ZenFlow Sanctuary",
    company: "Personal Project",
    period: "2025",
    location: "",
    description: "A modern web application designed to enhance focus and productivity through ambient sound mixing and Pomodoro time management.",
    icon: Headphones,
    category: "Dev",
    technologies: ["React 18", "TypeScript", "Tailwind CSS", "Vite", "Radix UI", "Cloudinary"],
    highlights: ["Advanced Sound Mixer with 20+ ambient sounds", "Customizable Pomodoro Timer", "Scene Saving & Glassmorphism UI"],
    status: "Completed",
    images: ["https://res.cloudinary.com/dvmuvjukn/image/upload/v1766057870/Capture_d_%C3%A9cran_2025-12-18_123000_sj9qkp.png"],
    githubUrl: "https://github.com/m2l33k/ZenFLow"
  },
  {
    title: "Code Arena AI: Multi-Agent Coding Tournament",
    company: "Personal Project",
    period: "November 2025",
    location: "",
    description: "An advanced Multi-Agent System (MAS) where AI models compete to solve algorithmic problems with a Human-in-the-Loop architecture and real-time Web UI.",
    icon: Bot,
    category: "AI",
    technologies: ["Python 3.10+", "Ollama", "Llama 3.1", "Mistral", "GPT-4o", "Flask", "HTML/CSS"],
    highlights: ["Multi-Agent System with Hybrid Intelligence", "Real-time gamified battle UI", "Human-in-the-Loop architecture"],
    status: "Completed",
    images: ["https://res.cloudinary.com/dvmuvjukn/image/upload/v1766058091/generated-image_iknfnh.jpg", "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766058105/Capture_d_%C3%A9cran_2025-12-18_124111_vzghzq.png"],
    githubUrl: "https://github.com/m2l33k/SentenX"
  },
  {
    title: "Decentralized Swarm Logistics Simulation",
    company: "Personal Project",
    period: "Sep 2025",
    location: "",
    description: "A Python-based simulation of a decentralized fleet of autonomous delivery vehicles using swarm intelligence, a Proof-of-Authority blockchain, and a local Large Language Model (LLM) for strategic oversight.",
    icon: Network,
    category: "AI",
    technologies: ["Python 3.12+", "Ollama", "Llama 3:8b", "numpy", "pygame"],
    highlights: ["Three-tiered intelligence model", "Decentralized bidding protocol", "Energy-efficient PoA blockchain"],
    status: "In Development",
    images: ["https://res.cloudinary.com/dvmuvjukn/image/upload/v1766058347/Capture_d_%C3%A9cran_2025-12-18_124535_iqmteb.png"],
    githubUrl: "https://github.com/m2l33k/Strategy-Aware"
  },
  {
    title: "Offensive Message Filter System",
    company: "Personal Project",
    period: "2024",
    location: "",
    description: "An intelligent message filtering system designed to detect and filter offensive content in chat applications. The system uses machine learning to classify messages as either offensive or non-offensive.",
    icon: Shield,
    category: "AI",
    technologies: ["Python", "Machine Learning", "REST API", "Angular"],
    highlights: ["Real-time offensive content filtering", "ML-based classification", "REST API integration"],
    status: "Completed",
    images: ["https://corp-backend.brevo.com/wp-content/uploads/2024/07/How-do-spam-filters-work.png"],
    githubUrl: "https://github.com/m2l33k/filtre-chain"
  },
  {
    title: "Cyber Sentinel - Advanced Security Analysis Tool",
    company: "Personal Project",
    period: "2024",
    location: "",
    description: "A comprehensive security analysis platform that combines code scanning, network reconnaissance, and AI-powered vulnerability assessment into one integrated solution.",
    icon: Shield,
    category: "Cybersecurity",
    technologies: ["Python", "Semgrep", "Nmap", "AI/ML", "DNS Recon"],
    highlights: ["AI-powered vulnerability assessment", "Automated code scanning (Semgrep)", "Network reconnaissance & fuzzing"],
    status: "Completed",
    images: ["https://res.cloudinary.com/dvmuvjukn/image/upload/v1766058972/0d884e77-138f-4107-857d-cdb1c21b515f_h5pthx.jpg"],
    githubUrl: "https://github.com/m2l33k/ASAT"
  },
  {
    title: "ERP SYSTEM FOR ISO 9001 PROCESS AUTOMATION",
    company: "Cocosunult",
    period: "October 2024 – May 2025",
    location: "ESPRIT",
    description: "Integrated an ERP system to automate ISO 9001 compliance, reducing manual work by 60% and improving quality management through real-time reporting.",
    icon: Briefcase,
    category: "Dev",
    technologies: ["SpringBoot", "Angular 19 ", "PostgreSQL", "Maven", "Git", "Jenkins", "Docker", "Kubernetes", "Jira" , "keycloack" , "Mysql" , "PostgreSQL"],
    highlights: ["60% reduction in manual work", "Real-time compliance reporting", "Quality management automation"],
    status: "Completed",
    images: ["https://res.cloudinary.com/dvmuvjukn/image/upload/v1766057205/Solution_1_yr6jfp.jpg", "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766057203/Capture_d_%C3%A9cran_2025-05-11_203439_f777hs.png"]
  },
  {
    title: "AI-DRIVEN CYBERSECURITY INCIDENT RESPONSE PLATFORM",
    company: "IEEE",
    period: "July 2024 – Sep 2024",
    location: "",
    description: "Designed an AI/ML-based platform for automated threat analysis, integrating Snort/Suricata to accelerate incident response by 35%",
    icon: Shield,
    category: "AI",
    technologies: ["Python", "Scikit-learn", "Snort", "Suricata", "Pandas", "NumPy", "Jupyter Notebook"],
    highlights: ["35% faster incident response", "Automated threat analysis", "ML-based detection"],
    status: "Completed",
    images: ["https://res.cloudinary.com/dvmuvjukn/image/upload/v1766059422/Screenshot_2024-11-10_06_39_04_1_d6wzgr.png"]
  },
  {
    title: "TechPioneers",
    company: "Personal Project",
    period: "2024",
    location: "",
    description: "An educational e-learning platform focused on delivering modern software engineering courses and interactive learning experiences.",
    icon: Briefcase,
    category: "Dev",
    technologies: ["Symfony 6", "MySQL", "HTML", "CSS", "JavaScript"],
    highlights: ["Educational e-learning platform", "Modern software engineering focus"],
    status: "Completed",
    images: ["https://res.cloudinary.com/dvmuvjukn/image/upload/v1766057105/Capture_d_%C3%A9cran_2024-12-19_195218_qbnrmj.png", "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766057104/Capture_d_%C3%A9cran_2024-12-10_195042_pomejt.png"],
    githubUrl: "https://github.com/m2l33k/techPioneers"
  },
  {
    title: "BASIC NETWORK SNIFFER",
    company: "Personal Project",
    period: "2024",
    location: "",
    description: "An initial phase of network traffic monitoring to detect suspicious activities in cybersecurity.",
    icon: Network,
    category: "Cybersecurity",
    technologies: ["Python", "Scapy"],
    highlights: ["Network traffic monitoring", "Suspicious activity detection"],
    status: "Completed",
    images: ["https://res.cloudinary.com/dvmuvjukn/image/upload/v1766059611/e680537d-7085-4064-8a85-7447424300ad_dqbwjx.jpg"]
  },
  {
    title: "Phishing Awareness Training",
    company: "Personal Project",
    period: "2024",
    location: "",
    description: "A training program designed to raise awareness and prevent phishing attacks through interactive sessions.",
    icon: Shield,
    category: "Cybersecurity",
    technologies: [],
    highlights: ["Interactive training sessions", "Phishing attack prevention"],
    status: "Completed",
    images: ["https://res.cloudinary.com/dvmuvjukn/image/upload/v1766059695/d63a90bf-81ed-4ea2-bc0e-1e4eb24a69e0_soqtgs.jpg"]
  },
  {
    title: "NextJEEL",
    company: "Personal Project",
    period: "2024",
    location: "",
    description: "A web development project focused on creating a modern, responsive platform for interactive learning.",
    icon: Briefcase,
    category: "Dev",
    technologies: ["React.js"],
    highlights: ["Modern & responsive platform", "Interactive learning focus"],
    status: "Completed",
    images: ["https://res.cloudinary.com/dvmuvjukn/image/upload/v1766057146/Capture_d_%C3%A9cran_2024-12-08_223405_i5pu0b.png", "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766057135/Capture_d_%C3%A9cran_2024-12-10_194913_e21wqo.png" , "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766057133/Capture_d_%C3%A9cran_2024-12-10_194924_kw3p2o.png" , "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766057123/Capture_d_%C3%A9cran_2024-12-10_194955_hjg5pk.png"]
  },
  {
    title: "Luducatio - Robot éducatif pour l'apprentissage des échecs",
    company: "Personal Project",
    period: "2024",
    location: "",
    description: "An educational web project integrating a robotic platform for chess learning and skill-building.",
    icon: Briefcase,
    category: "AI",
    technologies: ["python" , "machine learning" , "opencv"],
    highlights: ["Robotic platform integration", "Chess learning application"],
    status: "Completed",
    images: ["https://res.cloudinary.com/dvmuvjukn/image/upload/v1766059909/82b965d8-6669-40ea-bacc-afd6925b0475_mdodr3.jpg"],
    githubUrl: "https://github.com/m2l33k/ChessRobot"
  },
];

export const internships: Internship[] = [
  {
    company: "OXYNAS",
    role: "INTERN IN AI-POWERED WEB APPLICATION PENTESTING",
    period: "June 2025 – August 2025",
    location: "Paris / Remote",
    description: "Developed an AI-powered penetration testing agent designed to automate the security assessment of web applications Integrated advanced vulnerability scanning techniques enhanced by machine learning to identify potential threats more efficiently Achieved higher detection accuracy while significantly reducing manual testing time, streamlining the overall security testing process",
    logoUrl: "oxynas-logo-slogan.png",
    companyUrl: "https://oxynas.com/",
    technologies: ["AI", "Web Security", "Python", "Automation"],
    certificateUrl: "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766060184/Capture_d_%C3%A9cran_2025-12-18_131425_kcqq6t.png"
  },
  {
    company: "ESPRIT",
    role: "BLOCKCHAIN & AI RESEARCH INTERN – SMART GRID SECURITY",
    period: "July 2025 – Present",
    location: "Tunis, Tunisia",
    description: "Developed a blockchain-based solution for smart grid security, analyzing performance, reliability, and latency in a simulated environment, achieving a benchmark latency of 49.5 ms for anomaly detection in the model.",
    logoUrl: "https://res.cloudinary.com/dvmuvjukn/image/upload/v1724034102/My-Resume/sdwjguyjgdvlkw3cmh56.png",
    companyUrl: "https://esprit.tn",
    technologies: ["Blockchain", "AI", "Smart Grid", "Security Research"],
    certificateUrl: "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766060218/WhatsApp_Image_2025-12-18_at_13.16.30_s57ofs.jpg"
  },
  {
    company: "TALAN-TUNISIA",
    role: "PENTESTING WEB APPLICATION INTERN",
    period: "June 2024 – September 2024",
    location: "Tunis, Tunisia",
    description: "Enhanced ZAP Proxy-based pentesting through automation and custom scripts, accelerating vulnerability assessment.",
    logoUrl: "image-removebg-preview(16).png",
    companyUrl: "https://talan.com",
    technologies: ["OWASP ZAP", "Python", "Web Security", "Automation"],
    certificateUrl: "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766060199/Capture_d_%C3%A9cran_2025-12-18_131434_qjcrmc.png"
  },
  {
    company: "ESPRIT",
    role: "PENTESTING WIFI/BLUETOOTH INTERN",
    period: "June 2024 – August 2024",
    location: "Tunis, Tunisia",
    description: "Simulated wireless network attacks, identified vulnerabilities, and implemented countermeasures, reducing the attack surface by 40%.",
    logoUrl: "https://res.cloudinary.com/dvmuvjukn/image/upload/v1724034102/My-Resume/sdwjguyjgdvlkw3cmh56.png",
    companyUrl: "https://esprit.tn",
    technologies: ["Wireless Security", "Bluetooth Security", "Network Attacks", "Countermeasures"],
    certificateUrl: "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766060203/Capture_d_%C3%A9cran_2025-12-18_131442_r92h0t.png"
  },
];

export const certifications: Certification[] = [
  {
    name: "Fundamentals of Deep Learning",
    issuer: "NVIDIA",
    date: "2025",
    status: "Active",
    credentialId: "1tO0Ys3ITkGJkXM3sgBKrQ",
    description: "Deep learning fundamentals and practical implementation using Python",
    skills: ["Deep Learning", "Python", "Neural Networks", "AI Development"],
    url: "https://learn.nvidia.com/certificates?id=1tO0Ys3ITkGJkXM3sgBKrQ",
    category: "AI",
    issuerLogoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/21/Nvidia_logo.svg",
    imageUrl: "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766062573/Capture_d_%C3%A9cran_2025-12-18_133650_axmqmq.png"
  },
  {
    name: "Evaluation and Light Customization of Large Language Models",
    issuer: "NVIDIA",
    date: "2025",
    status: "Active",
    credentialId: "M9kdR7yQQ5WiuvosdW_R4g",
    description: "Evaluation and light customization of large language models",
    skills: ["Large Language Models", "Evaluation", "Customization"],
    url: "https://learn.nvidia.com/certificates?id=M9kdR7yQQ5WiuvosdW_R4g",
    category: "AI",
    issuerLogoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/21/Nvidia_logo.svg",
    imageUrl : "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766062259/Capture_d_%C3%A9cran_2025-12-18_133555_zkr4yk.png"
  },
  {
    name: "Building RAG Agents with LLMs",
    issuer: "NVIDIA",
    date: "2025",
    status: "Active",
    credentialId: "qjskPdObSiC6MS5RlXreLA",
    description: "Building Retrieval Augmented Generation (RAG) agents using Large Language Models.",
    skills: ["RAG", "LLMs", "Generative AI", "LangChain"],
    url: "https://learn.nvidia.com/certificates?id=qjskPdObSiC6MS5RlXreLA",
    category: "AI",
    issuerLogoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/21/Nvidia_logo.svg",
    imageUrl: "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766061577/Capture_d_%C3%A9cran_2025-12-18_133407_litasi.png"
  },
  {
    name: "Getting Started with AI on Jetson Nano",
    issuer: "NVIDIA",
    date: "2025",
    status: "Active",
    credentialId: "GnzRATHpSIajte8xXpnjoA",
    description: "Fundamentals of AI and deep learning on NVIDIA Jetson Nano.",
    skills: ["Edge AI", "Jetson Nano", "Deep Learning", "Computer Vision"],
    url: "https://learn.nvidia.com/certificates?id=GnzRATHpSIajte8xXpnjoA",
    category: "AI",
    issuerLogoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/21/Nvidia_logo.svg",
    imageUrl: "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766061783/Capture_d_%C3%A9cran_2025-12-18_133421_xtnv7j.png"
  },
  {
    name: "AppSec (CAP)",
    issuer: "The SECOPS GROUP",
    date: "2025",
    status: "Active",
    credentialId: "10087776",
    description: "Application security fundamentals and secure development practices",
    skills: ["Application Security", "Secure Coding", "OWASP", "Vulnerability Assessment"],
    url: "https://pentestingexams.com/certificate-validation/",
    category: "Cybersecurity",
    issuerLogoUrl: "https://secops.group/wp-content/uploads/2024/03/logo-pentesting-services-pentesting-exams.png",
    imageUrl : "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766062273/Capture_d_%C3%A9cran_2025-12-18_133612_scjsyh.png"
  },
  {
    name: "Scrum Foundation",
    issuer: "CertiProf",
    date: "2024",
    status: "Active",
    credentialId: "8440a79c-603f-485b-9f98-8fca213a817c",
    description: "Agile project management and Scrum methodology fundamentals",
    skills: ["Agile Development", "Scrum", "Project Management", "Team Collaboration"],
    url: "https://www.credly.com/badges/8440a79c-603f-485b-9f98-8fca213a817c/public_url",
    category: "Dev",
    issuerLogoUrl: "https://certiprof.com/cdn/shop/files/CertiProf-Logo_200x.png"
  },
  {
    name: "Hashgraph Developer",
    issuer: "The Hashgraph Association",
    date: "2025",
    status: "Active",
    credentialId: "2d0ed167-0b26-41b3-a16d-5d373cd4463b",
    description: "Hashgraph development and implementation",
    skills: ["Hashgraph", "Development", "Implementation", "Smart Contracts"],
    url: "https://certs.hashgraphdev.com/2d0ed167-0b26-41b3-a16d-5d373cd4463b.pdf",
    category: "Dev",
    issuerLogoUrl: "https://import.cdn.thinkific.com/134097%2Fcustom_site_themes%2Fid%2F73zuG3fHQRigUmlmhQql_bta-new-logo.png",
    imageUrl : "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766062332/Capture_d_%C3%A9cran_2025-12-18_133619_zclayl.png"
  },
  {
    name: "Oracle AI Vector Search Certified Professional",
    issuer: "Oracle",
    date: "2025",
    status: "Active",
    credentialId: "3E1FD1803CC8A032863018AAA3A21D25C6D09345062A6BFB2848FF12D7C94AAE",
    description: "AI vector search implementation and optimization",
    skills: ["AI", "Vector Search", "Implementation", "Optimization"],
    url: "https://catalog-education.oracle.com/pls/certview/sharebadge?id=3E1FD1803CC8A032863018AAA3A21D25C6D09345062A6BFB2848FF12D7C94AAE",
    category: "AI",
    issuerLogoUrl: "https://upload.wikimedia.org/wikipedia/commons/5/50/Oracle_logo.svg",
    imageUrl: "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766062255/Capture_d_%C3%A9cran_2025-12-18_133548_actqdp.png"
  },
  {
    name: "Cisco Cybersecurity",
    issuer: "Cisco",
    date: "2024",
    status: "Active",
    credentialId: "a48a3270-e587-47a0-ad30-9a183c5c4c42",
    description: "Network security fundamentals and Cisco security technologies",
    skills: ["Network Security", "Cisco Technologies", "Threat Detection", "Security Protocols"],
    url: "https://www.credly.com/badges/a48a3270-e587-47a0-ad30-9a183c5c4c42/public_url",
    category: "Cybersecurity",
    issuerLogoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/08/Cisco_logo_blue_2016.svg",
    imageUrl : "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766062595/Capture_d_%C3%A9cran_2025-12-18_133720_ldpf4j.png"
  },
  {
    name: "Github Foundation",
    issuer: "GitHub",
    date: "2025",
    status: "Active",
    credentialId: "2307d695-4e5c-4488-8578-7cda57c82d0a",
    description: "Version control and collaborative development with Git and GitHub",
    skills: ["Version Control", "Git", "GitHub", "Collaborative Development"],
    url: "https://www.credly.com/badges/2307d695-4e5c-4488-8578-7cda57c82d0a/public_url",
    category: "Dev",
    issuerLogoUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c2/GitHub_Invertocat_Logo.svg",
    imageUrl : "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766063863/Capture_d_%C3%A9cran_2025-12-18_141358_af8iqq.png"
  },
  {
    name: "TryHackMe Pre Security",
    issuer: "TryHackMe",
    date: "2025",
    status: "Active",
    credentialId: "THM-PRESEC-001",
    description: "Cybersecurity fundamentals and ethical hacking basics",
    skills: ["Cybersecurity Basics", "Ethical Hacking", "Network Security", "Linux"],
    url: "https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-YALUUJOW4H.pdf",
    category: "Cybersecurity",
    issuerLogoUrl: "https://assets.tryhackme.com/img/THMlogo.png",
    imageUrl : "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766063874/Capture_d_%C3%A9cran_2025-12-18_141703_epurbc.png"
  },
  {
    name: "IBM Data Visualization",
    issuer: "IBM",
    date: "2024",
    status: "Active",
    credentialId: "3e8597df-085b-4c34-be6a-a47a657f93b6",
    description: "Data visualization techniques and business intelligence",
    skills: ["Data Visualization", "Business Intelligence", "Analytics", "Dashboard Design"],
    url: "https://www.credly.com/badges/3e8597df-085b-4c34-be6a-a47a657f93b6/public_url",
    category: "Dev",
    issuerLogoUrl: "https://upload.wikimedia.org/wikipedia/commons/5/51/IBM_logo.svg" , 
    imageUrl : "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766064544/Capture_d_%C3%A9cran_2025-12-18_142747_phfbwv.png"
  },
  {
    name: "DevSecOps Learning",
    issuer: "TryHackMe",
    date: "2025",
    status: "Active",
    credentialId: "DEVSECOPS-001",
    description: "Security integration in DevOps pipelines and secure development",
    skills: ["DevSecOps", "CI/CD Security", "Infrastructure as Code", "Security Automation"],
    url: "https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-YALUUJOW4H.pdf",
    category: "Cybersecurity",
    issuerLogoUrl: "https://assets.tryhackme.com/img/THMlogo.png",
    imageUrl : "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766063868/Capture_d_%C3%A9cran_2025-12-18_141503_simms7.png"
  },
  {
    name: "Python Essentials 1",
    issuer: "Python Institute",
    date: "2025",
    status: "Active",
    credentialId: "054bf6b2-8d3d-468e-a078-ec3473a2afff",
    description: "Foundational concepts of computer programming and the Python language.",
    skills: ["Python", "Programming Basics", "Data Types", "Control Flow"],
    url: "https://www.credly.com/badges/054bf6b2-8d3d-468e-a078-ec3473a2afff/public_url",
    category: "Dev",
    issuerLogoUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg",
    imageUrl : "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766064528/Capture_d_%C3%A9cran_2025-12-18_142832_gbgtcz.png"
  },
  {
    name: "AI for Anomaly Detection",
    issuer: "NVIDIA",
    date: "2025",
    status: "Active",
    credentialId: "TDSSTGVqTMmdSBKhU66_bg",
    description: "Implementing AI models for detecting anomalies in industrial data.",
    skills: ["AI", "Anomaly Detection", "Deep Learning", "Industrial IoT"],
    url: "https://learn.nvidia.com/certificates?id=TDSSTGVqTMmdSBKhU66_bg",
    category: "AI",
    issuerLogoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/21/Nvidia_logo.svg",
    imageUrl: "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766061789/Capture_d_%C3%A9cran_2025-12-18_133434_q0r49c.png"
  },
  {
    name: "Generative AI with Diffusion Models",
    issuer: "NVIDIA",
    date: "2025",
    status: "Active",
    credentialId: "PdQJK76xS2OHwU0Yn_AIWA",
    description: "Deep dive into generative AI and diffusion models.",
    skills: ["Generative AI", "Diffusion Models", "Computer Vision", "Deep Learning"],
    url: "https://learn.nvidia.com/certificates?id=PdQJK76xS2OHwU0Yn_AIWA",
    category: "AI",
    issuerLogoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/21/Nvidia_logo.svg",
    imageUrl : "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766061801/Capture_d_%C3%A9cran_2025-12-18_133450_ogslwd.png"
  },
  {
    name: "AI for Predictive Maintenance",
    issuer: "NVIDIA",
    date: "2025",
    status: "Active",
    credentialId: "HTAHASfdRuekTxCPxk5QfA",
    description: "Using AI to predict equipment failures and optimize maintenance.",
    skills: ["Predictive Maintenance", "Time Series Analysis", "AI", "Industrial AI"],
    url: "https://learn.nvidia.com/certificates?id=HTAHASfdRuekTxCPxk5QfA#",
    category: "AI",
    issuerLogoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/21/Nvidia_logo.svg",
    imageUrl : "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766061795/Capture_d_%C3%A9cran_2025-12-18_133443_hqdns0.png"
  },
  {
    name: "Ethical Hacker",
    issuer: "Cisco",
    date: "2025",
    status: "Active",
    credentialId: "d99c8f70-d850-4db5-a0f8-8f95d57b6623",
    description: "Proficiency in offensive security testing and ethical hacking methodologies.",
    skills: ["Ethical Hacking", "Penetration Testing", "Security Assessment", "Vulnerability Analysis"],
    url: "https://www.credly.com/badges/d99c8f70-d850-4db5-a0f8-8f95d57b6623/public_url",
    category: "Cybersecurity",
    issuerLogoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/08/Cisco_logo_blue_2016.svg",
    imageUrl : "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766064047/Capture_d_%C3%A9cran_2025-12-18_142033_dhfegq.png"
  },
  {
    name: "AWS Training Badge",
    issuer: "AWS",
    date: "2025",
    status: "Active",
    credentialId: "c8c788e5-d0d9-4723-95b4-e78d4c268aec",
    description: "Fundamental understanding of AWS Cloud concepts and services.",
    skills: ["Cloud Computing", "AWS Services", "Cloud Security", "Infrastructure"],
    url: "https://www.credly.com/badges/c8c788e5-d0d9-4723-95b4-e78d4c268aec/public_url",
    category: "Dev",
    issuerLogoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg" , 
    imageUrl : "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766064538/Capture_d_%C3%A9cran_2025-12-18_142706_grdmhk.png"
  },
  {
    name: "Networking Basics",
    issuer: "Cisco",
    date: "2025",
    status: "Active",
    credentialId: "9fd70672-a3d4-4f9e-965b-a0e595643164",
    description: "Foundational knowledge of network protocols, devices, and operations.",
    skills: ["Networking", "TCP/IP", "OSI Model", "Network Troubleshooting"],
    url: "https://www.credly.com/badges/9fd70672-a3d4-4f9e-965b-a0e595643164/public_url",
    category: "Cybersecurity",
    issuerLogoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/08/Cisco_logo_blue_2016.svg",
    imageUrl : "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766063929/Capture_d_%C3%A9cran_2025-12-18_141233_qeltyb.png"
  },
  {
    name: "Natural Language Processing",
    issuer: "NVIDIA",
    date: "2025",
    status: "Active",
    credentialId: "9Pfvt0O-Sz29etyyFrXRFw",
    description: "Modern NLP techniques using deep learning and transformers.",
    skills: ["NLP", "Transformers", "BERT", "Text Classification"],
    url: "https://learn.nvidia.com/certificates?id=9Pfvt0O-Sz29etyyFrXRFw",
    category: "AI",
    issuerLogoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/21/Nvidia_logo.svg",
    imageUrl: "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766061778/Capture_d_%C3%A9cran_2025-12-18_133414_wq08hg.png"
  },
  {
    name: "Junior Cybersecurity Analyst",
    issuer: "Cisco",
    date: "2025",
    status: "Active",
    credentialId: "213294e0-c258-4c39-acda-2036a43982bf",
    description: "Entry-level cybersecurity operations and incident response.",
    skills: ["Security Operations", "Incident Response", "Threat Analysis", "Network Security"],
    url: "https://www.credly.com/badges/213294e0-c258-4c39-acda-2036a43982bf/public_url",
    category: "Cybersecurity",
    issuerLogoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/08/Cisco_logo_blue_2016.svg",
    imageUrl : "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766061968/Capture_d_%C3%A9cran_2025-12-18_133518_mfdouk.png"
  },
  {
    name: "Lifelong Learning 2025",
    issuer: "CertiProf",
    date: "2025",
    status: "Active",
    credentialId: "1f5ae449-0f69-4587-b700-a41ebd54178c",
    description: "Demonstrated unwavering commitment to lifelong learning, open-mindedness, and continuous professional development in the digital world.",
    skills: ["Lifelong Learning", "Career Development", "Growth Mindset", "Continuing Education", "Professional Ethics"],
    url: "https://www.credly.com/badges/1f5ae449-0f69-4587-b700-a41ebd54178c/public_url",
    category: "Dev",
    issuerLogoUrl: "https://certiprof.com/cdn/shop/files/CertiProf-Logo_200x.png",
    imageUrl: "https://res.cloudinary.com/dvmuvjukn/image/upload/v1766064699/lifelong-learning-2025_zj6bql.png"
  }
];
